markdown: kramdown
baseurl: 
permalink: pretty
exclude: ['README.md']
collections: 
  projects: 
    order: 
      - give.md
      - broadtime.md
      - maxxmockup.md
    output: true
defaults: 
  - scope: 
      path: ""
      type: "projects"
    values: 
      layout: "project"
      button1text: "Demo"
      button2text: "View Source"
  - scope: 
      path: ""
    values: 
      layout: "default"
plugins: 
  - github-pages